name: "Israeli Bank FireFly iii Importer"
description: "Using Israeli bank scrapper and import the data into free and open source FireFly iii."
version: "1.3.6"
slug: "israeli-bank-firefly-importer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  firefly_base_url: 'http://homeassistant.local:3473'
  firefly_token_api: ''
  config_file: '/config/israeli-bank-firefly-importer/config.yaml'
  cron: '0 6 * * *'
schema:
  firefly_base_url: str
  firefly_token_api: str
  config_file: str
  cron: str
map:
  - "config:rw"
